version: "3"
services:
  webui:
    build: ./webui
    volumes:
      - frontbuild:/webui/dist
    networks:
        - knockknock
  api:
    build: ./webapp
    ports:
      - 8080:5000
    volumes:
      - frontbuild:/usr/src/webui
    command: ['./wait-for-it.sh', 'database:3306', '--', 'python', 'app.py']
    depends_on:
      - database
      - webui
    networks:
        - knockknock
  database:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=password
      - MYSQL_DATABASE=knockknock
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
        - knockknock

volumes:
  frontbuild:
networks:
    knockknock:
        driver: bridge
    
