############################
# Date        : dim. 03 juin 2018 14:26:24 CEST
# Version     : 0.0.1
# Description : 0.0.1
FROM mariadb

ENV MYSQL_HOST 0.0.0.0
ENV MYSQL_USER admin
ENV MYSQL_DATABASE knockknock
ENV MYSQL_PASSWORD password
ENV MYSQL_RANDOM_ROOT_PASSWORD yes

EXPOSE 3306

