FROM armhf/python:3.5

WORKDIR /usr/src/webapp

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN ln -sfv $PWD/usr/src/webapp/webui/index.html /usr/src/webapp/templates
RUN ln -sfv $PWD/usr/src/webapp/webui/static /usr/src/webap


EXPOSE 5000

CMD [ "python", "./app" ]
