# Tokens
SECRET_KEY="3ZE2xL9D4M+1WyTjs1h2YobJSMJZxoFQpqsT6VAcFRs="

# DATABASE
MYSQL_DATABASE_HOST="0.0.0.0"
MYSQL_DATABASE_USER="admin"
MYSQL_DATABASE_PASSWORD="password"
MYSQL_DATABASE_DB="knockknock"

# JWT
JWT_SECRET="secret"
JWT_ALGORITHM="HS256"
