#!/bin/bash
# Author      : github.com/TonyChG
# Date        : Sat 02 Jun 2018 12:30:44 PM CEST
# Version     : 0.0.1
# Description :

test -f $(which python3.5) &&
  virtualenv --python=python3.5 pyenv35 > /dev/null \
  && echo "pyenv35/bin/activate" 
