#!/bin/bash
# Author      : github.com/TonyChG
# Date        : Sat 02 Jun 2018 12:30:44 PM CEST
# Version     : 0.0.1
# Description :

case "$1" in
  create)
    export MYSQL_DATABASE_HOST="0.0.0.0"
    export MYSQL_DATABASE_USER="admin"
    export MYSQL_DATABASE_PASSWORD="password"
    export MYSQL_DATABASE_DB="knockknock"
    export FLASK_ENV="development"
    test -f $(which python3.5) &&
      virtualenv --python=python3.5 pyenv35 > /dev/null \
      && echo "pyenv35/bin/activate" 
    ;;
  export)
    pip install -r requirements.txt
    ;;
  *)
    >&2 echo  "Usage: $0 export | source \$($0 create)"
esac
